import {
  randomItemFromArraySimple,
  randomItemFromTable,
} from '../utils/helpers.js';
import { swords, weapons } from '../lists/weapons.js';
import { damageTypes } from '../lists/other.js';

const magicItems = {
  11: () => `Weapon, +2 ${randomItemFromArraySimple(weapons)}`,
  14: randomItemFromTable(8, {
    1: 'Figurine of wondrous power, Bronze griffon',
    2: 'Figurine of wondrous power, Ebony fly',
    3: 'Figurine of wondrous power, Golden lions',
    4: 'Figurine of wondrous power, Ivory goats',
    5: 'Figurine of wondrous power, Marble elephant',
    7: 'Figurine of wondrous power, Onyx dog',
    8: 'Figurine of wondrous power, Serpentine owl',
  }),
  15: 'Adamantine armor (breastplate)',
  16: 'Adamantine armor (splint)',
  17: 'Amulet of health',
  18: 'Armor of vulnerability',
  19: 'Arrow-catching shield',
  20: 'Belt of dwarvenkind',
  21: 'Belt of hill giant strength',
  22: 'Berserker axe',
  23: 'Boots of levitation',
  24: 'Boots of speed',
  25: 'Bowl of commanding water elementals',
  26: 'Bracers of defense',
  27: 'Brazier of commanding fire elementals',
  28: 'Cape of the mounteback',
  29: 'Censer of controlling air elementals',
  30: 'Armor, +1 chain mail',
  31: () =>
    `Armor of resistance (chain mail), ${randomItemFromArraySimple(
      damageTypes
    )}`,
  32: 'Armor, +1 (chain shirt)',
  33: () =>
    `Armor of resistance (chain shirt), ${randomItemFromArraySimple(
      damageTypes
    )}`,
  34: 'Cloak of displacement',
  35: 'Cloak of the bat',
  36: 'Cube of force',
  37: "Daern's instant fortress",
  38: 'Dagger of venom',
  39: 'Dimensional shackles',
  40: () => `Dragon slayer, ${randomItemFromArraySimple(swords)}`,
  41: 'Elven chain',
  42: () => `Flame tongue, ${randomItemFromArraySimple(swords)}`,
  43: 'Gem of seeing',
  44: () =>
    `Giant slayer, ${randomItemFromArraySimple([
      ...swords,
      'battleaxe',
      'handaxe',
    ])}`,
  45: 'Glamoured studded leather',
  46: 'Helm of teleportation',
  47: 'Horn of blasting',
  48: randomItemFromTable(75, {
    40: 'Horn of Valhalla (silver)',
    75: 'Horn of Valhalla (brass)',
  }),

  49: 'Instrument of the bards (Canaith mandolin)',
  50: 'Instrument of the bards (Cli lyre)',
  51: 'Ioun stone (awareness)',
  52: 'Ioun stone (protection)',
  53: 'Ioun stone (reserve)',
  54: 'Ioun stone (sustenance)',
  55: 'Iron bands of Bilarro',
  56: 'Armor, +1 leather',
  57: () =>
    `Armor of resistance (leather), ${randomItemFromArraySimple(damageTypes)}`,
  58: 'Mace of disruption',
  59: 'Mace of smiting',
  60: 'Mace of terror',
  61: 'Mantle of spell resistance',
  62: 'Necklace of prayer beads',
  63: 'Periapt of proof against poison',
  64: 'Ring of animal influence',
  65: 'Ring of evasion',
  66: 'Ring of feather failing',
  67: 'Ring of free action',
  68: 'Ring of protection',
  69: () => `Ring of resistance, ${randomItemFromArraySimple(damageTypes)}`,
  70: 'Ring of spell storing',
  71: 'Ring of the ram',
  72: 'Ring of X-ray vision',
  73: 'Robe of eyes',
  74: 'Rod of rulership',
  75: 'Rod of the pact keeper',
  76: 'Rope of entanglement',
  77: 'Armor, +1 scale mail',
  78: () =>
    `Armor of resistance (scale mail), ${randomItemFromArraySimple(
      'Acid',
      'Cold',
      'Fire',
      'Force',
      'Lightning',
      'Necrotic',
      'Poison',
      'Psychic',
      'Radiant',
      'Thunder'
    )}`,
  79: 'Shield, +1',
  80: 'Shield of missile attraction',
  81: 'Staff of charming',
  82: 'Staff of healing',
  83: 'Staff of swarming insects',
  84: 'Staff of the woodlands',
  85: 'Staff of withering',
  86: 'Stone of controlling earth elementals',
  87: 'Sun blade',
  88: () => `Sword of life stealing, ${randomItemFromArraySimple(swords)}`,
  89: () => `Sword of wounding, ${randomItemFromArraySimple(swords)}`,
  90: 'Tentacle rod',
  91: () => `Vicious weapon, ${randomItemFromArraySimple(weapons)}`,
  92: 'Wand of binding',
  93: 'Wand of enemy detection',
  94: 'Wand of fear',
  95: 'Wand of fireballs',
  96: 'Wand of lightning bolt',
  97: 'Wand of paralysis',
  98: 'Wand of the war mage, +2',
  99: 'Wand of wonder',
  100: 'Wings of flying',
};

export const magicItemsG = randomItemFromTable(100, magicItems);
